### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manuelap-msft**
Updated the Read Me file with the About this Repo section. Please have a read through before merging and let me know if that works!

### CODE REVIEW

**Comment by rpothin** [comment]
Hello @manuelap-msft,

Small suggestion, if I can: it could be interesting to have a line about the **Discussions** tab in the new **About this GitHub repo** section of the README.md.
Issues can be used for bugs or new features (from Microsoft's team), but for questions, discussions around Power Platform governance or even suggestion of new features I think people should go through the **Discussions** tab.

Thank you very much for your great work with the CoE 😊

**Comment by manuelap-msft** [comment]
@rpothin Great idea! I added a line on discussions, but it kept it to ideas around the CoE Starter Kit solutions. I think overall Power Platform governance that's not related to our solutions should continue to get discussed in our community where there's much broader reach (https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/bd-p/Admin_PowerApps). Let me know what you think!

**Comment by jenschristianschroder** [comment]
@manuelap-msft, I think we should copy the content of the CONTRIBUTE.md into the section on contribution in the README.md and remove the default MS contribution info as this is also in HOW_TO_CONTRIBUTE.md.
This would maybe add a little bit of duplicate content on Issues and Discussions that needs to be cleaned up.

Alternatively link to the CONTRIBUTE.md in the contribute section of the REAMDE.md

**Comment by manuelap-msft** [comment]
@jenschristianschroder Yes, agree - there's some duplication also between this About section and the contribute.md - I like the format you have in contribute.md with the sub-headers (vs the bullet list). I have made changes to bring them together now, let me know what you think!

**Review by jenschristianschroder — APPROVED** [review]

**Pull request merged**
