### PR TITLE
Get top 1000 projects instead of top 100 in ADO

### PR DESCRIPTION
**Pull request by winterscar**
This isn't really a substitute for proper pagination, but it should fix the issue for 99.9% of all organizations.

### CODE REVIEW

**Comment by devkeydet** [comment]
@winterscar - while we haven't published our contributors guide yet, maybe you can help us get there faster.  An old draft exists here:
https://github.com/microsoft/coe-starter-kit/tree/contribution-guide

We won't accept PRs into main because we follow a convention of using "dev" or "vnext" branches.  Our main branch represents the code for the latest release on the releases tab.
https://github.com/microsoft/coe-starter-kit/releases

So, for this you would need to submit a PR into this branch.
https://github.com/microsoft/coe-starter-kit/tree/ALMAcceleratorForAdvancedMakers
And you would need to make sure your "feature" or "work item" branch is based off it to minimize the likelihood of merge conflicts.  That branch represents the work in progress towards the next release.  Said another way, it is the "main branch for the next release of the solution".

Finally, we won't accept arbitrary PRs.  We, instead, want contributors to create an issue or find an existing issue and #issue-number in the PR before we review it.  There is already an issue loosely related to this:
https://github.com/microsoft/coe-starter-kit/issues/120

The original issue is an enhancement for paging.  We ran into some issues with the paging approach in private preview, which is why we deprioritized it.  But I am thinking you should create a new issue that just highlights the bug and asks for 1000 as a quick fix.  I'd be happy to accept the PR as a contribution if you can incorproate this feedback.

Today, all of our "dev" or "vnext" branches follow a naming convention of SolutionName.  However, we are considering adding "vnext" into the naming convention moving forward.   Since you are our first official PR from a fork, would you be up for volunteering to collaborate on the contribution guide?  If so, create an issue, we'll assign it to you, and we can collaborate.  For anything in the root, you can PR into main.  But for solution folders, we want you to PR into the vnext branch for that solution.

**Comment by devkeydet** [comment]
@winterscar - Awaiting your feedback.  If you want to update the PR, let us know.  If not, we can do the work to make the changes.

**Comment by winterscar** [comment]
Hey Marc! Apologies, I rushed to get this PR in and (obviously) didn't really give much thought to the contribution guidelines. I'll fix this up now.

**Comment by winterscar** [comment]
Closing and moving to https://github.com/microsoft/coe-starter-kit/pull/397

**Pull request closed without merging**
