### PR TITLE
App-Name does not use the available space in App Catalog. #2823

### PR DESCRIPTION
**Pull request by megel**
App-Name use now available space in App Catalog.
#2823

### CODE REVIEW

**Comment by megel** [comment]
Corrected also the `lblAvgRating.Width`, because it was shown like this before:
image

Now it is shown correctly:
image

**Comment by megel** [comment]
@mikefactorial can you support? Your pipeline seams to fail.

**Comment by mikefactorial** [comment]
@megel can you open an issue on this assigned to the ALM Accelerator? As of right now I don't believe Manuela and team are taking contributions but as an accelerator team this appears to be a permissions issue with outside contributors submitting PRs that I'd like to investigate further as we move towards a supportable contribution model.

**Comment by megel** [comment]
@mikefactorial I opened this issue: https://github.com/microsoft/coe-starter-kit/issues/2885

**Comment by mikefactorial** [comment]
Closing this out for now. This is good feedback, but not going to be merged. Please open an issue and share the changes with the team.

**Pull request closed without merging**
