### PR TITLE
Get top 1000 projects instead of top 100 in ADO

### PR DESCRIPTION
**Pull request by winterscar**
Re-submitting this request as per the discussion here https://github.com/microsoft/coe-starter-kit/pull/354.

This resolves https://github.com/microsoft/coe-starter-kit/issues/399.

This PR updates the OpenAPI definition for the CustomAzureDevOps connector to fetch 1000 projects by default, and allows the API consumer to override the value. 

Github is treating the json file as a binary, so it's not really diffing it properly, but I assume the change is correct.

### CODE REVIEW

**Comment by winterscar** [comment]
@devkeydet, the file encoding for the `cat_5Fcustomazuredevops_openapidefinition.json` file is UFT-16, (which is odd), and it means git won't diff the files correctly (It thinks the file is a binary)

I've checked my changes locally and things look good, but I'd advise you to do the same to validate.

**Comment by mikefactorial** [comment]
Thanks for resubmitting @winterscar! We have a fix for GitHub treating json as binary in the works #368. I'll work on getting this merged.

**Comment by winterscar** [comment]
No worries @mikefactorial. What is the fix you came up with?

**Comment by mikefactorial** [comment]
@winterscar I may have to manually merge your changes due to the merge conflicts and the json issue. FYI there's a step in our pipelines that formats our json files to make them readable I added encoding UTF8 to that process to fix #368. Unfortunately, it won't take hold until the target branches are all updated to be UTF8. 

```- powershell: |
   Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile  jq.exe
   Get-ChildItem -Path "$(Build.SourcesDirectory)\${{parameters.Repo}}\${{parameters.SolutionName}}\SolutionPackage" -Recurse -Filter *.json | 
   ForEach-Object {
    #skip canvas app folder because canvas team already handles this for canvas unpack
    if(-not $_.FullName.Contains('CanvasApps')) {
      Write-Host $_.FullName
      $formatted = .\jq.exe . $_.FullName --sort-keys
      $formatted | Out-File $_.FullName -Encoding UTF8
    }
   }
   del jq.exe
   del $(Build.ArtifactStagingDirectory)\${{parameters.SolutionName}}.zip
   del $(Build.ArtifactStagingDirectory)\${{parameters.SolutionName}}_managed.zip
  displayName: 'Format JSON files'
  enabled: true

**Comment by winterscar** [comment]
Hey Mike, thanks for the heads up about `jq`. And no worries about the manual merge. Want me to close this?

**Comment by mikefactorial** [comment]
@winterscar I'll close it out once the fix is in. Thanks

**Comment by mikefactorial** [comment]
@winterscar merged changes in #415. Thanks again for the contribution and working with us on this.

**Pull request closed without merging**
