### PR TITLE
Error Handling and New Deployment Settings UX

### LINKED ISSUE #608: [AA4AM] Error Handling in Canvas App
**Is your feature request related to a problem? Please describe.**
If something is stored in the User Settings and is removed from Azure DevOps later on an error will be thrown in the app. 

**Describe the solution you'd like**
We should handle missing data better to ensure that the user doesn't see errors when a resource is no longer available (e.g. Pull Requests, Projects etc.) Additionally, want to handle any errors related to connectors using IfError in the app

### PR DESCRIPTION
**Pull request by mikefactorial**
Fixes #608

### CODE REVIEW

**Comment by mikefactorial** [comment]
Fixes https://github.com/microsoft/coe-starter-kit/issues/1882
Fixes https://github.com/microsoft/coe-starter-kit/issues/2005

**Comment by mikefactorial** [comment]
Fixes #1388

**Comment by mikefactorial** [comment]
Fixes #1680

**Comment by mikefactorial** [comment]
Fixes #2299

**Review by manuelap-msft — APPROVED** [review]

**Pull request merged**
