### PR TITLE
Update AppDetailsScreen.fx.yaml

### PR DESCRIPTION
**Pull request by carfup**
Typo in the filter while adding permission to user (enviornment instead of environment)

### CODE REVIEW

**Comment by devkeydet** [comment]
We don't accept PRs into main. We need a contribution guide to make this clearer. See discussion here:
#354

For now, please update the PR to pull into the CenterofExcellenceCoreComponents branch.

**Comment by carfup** [comment]
Sorry Marc, I changed the target branch.

**Comment by mikefactorial** [comment]
Hey @carfup you'll need to make your changes in the same branch on your fork and PR from / to CenterofExcellenceCoreComponents. As @devkeydet mentioned we should have some guidance on this available soon to help avoid this confusion. Thanks

**Comment by mikefactorial** [comment]
@carfup Closing this for now based on the above comment. Feel free to create a new Issue for this and submit a new PR to associate the PR with.

**Pull request closed without merging**
